const { PrismaClient } = require("@prisma/client");
const { PrismaPg } = require("@prisma/adapter-pg");
const { Pool } = require("pg");
const path = require("path");
require("dotenv").config({ path: path.resolve(__dirname, "../../.env") });

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error("❌ DATABASE_URL is not set in .env");
  process.exit(1);
}

const pool = new Pool({ connectionString, ssl: { rejectUnauthorized: false } });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// MCQs are stored as { webdev: [...], cs: [...], english: [...], ... }
const mcqMap = require("../data/mcqs.json");

/**
 * Maps a course name to its MCQ category key in mcqs.json.
 * First checks for an exact sanitized-name match (covers all 46 categoryCourses),
 * then falls back to keyword-based category matching.
 */
function getCategoryKey(courseName) {
  // Sanitize to match the keys generated by extract-all-categories.js
  const sanitizedKey = courseName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

  // If a direct key exists in the MCQ map, use it
  if (mcqMap[sanitizedKey]) return sanitizedKey;

  // Keyword-based fallback for base categories
  const name = courseName.toLowerCase();

  if (name.includes("jee")) {
    if (name.includes("physics")) return "jee_physics";
    if (name.includes("chemistry")) return "jee_chemistry";
    if (name.includes("math") || name.includes("mathematics")) return "jee_math";
  }
  if (name.includes("neet")) {
    if (name.includes("biology")) return "neet_biology";
    if (name.includes("physics")) return "neet_physics";
    if (name.includes("chemistry")) return "neet_chemistry";
    return "neet_biology";
  }
  if (
    name.includes("web") || name.includes("html") ||
    name.includes("css") || name.includes("javascript") ||
    name.includes("development")
  ) {
    return "webdev";
  }
  if (
    name.includes("computer") || name.includes("gate") ||
    name.includes("database") || name.includes("sql")
  ) {
    return "cs";
  }
  if (name.includes("english") || name.includes("grammar") || name.includes("ctet")) {
    return "english";
  }
  if (
    name.includes("math") || name.includes("algebra") ||
    name.includes("nda") || name.includes("geometry")
  ) {
    return "math";
  }
  return "generic";
}


async function main() {
  console.log("🌱 Seeding MCQ questions...");

  // Load all courses once
  const courses = await prisma.course.findMany();
  if (courses.length === 0) {
    console.error("❌ No courses found. Run courses.seed.js first.");
    process.exit(1);
  }

  // Clear all existing MCQs for a clean seed
  const deleted = await prisma.mCQQuestion.deleteMany();
  console.log(`  ✓ Cleared ${deleted.count} existing MCQ questions`);

  let totalSeeded = 0;

  for (const course of courses) {
    const categoryKey = getCategoryKey(course.name);
    const questions = mcqMap[categoryKey];

    if (!questions || questions.length === 0) {
      console.warn(`  ⚠ No questions for category "${categoryKey}" (course: "${course.name}") — skipping`);
      continue;
    }

    console.log(
      `  → Seeding ${questions.length} questions for "${course.name}" [${categoryKey}]...`
    );

    // Insert in batches of 20
    const batchSize = 20;
    for (let i = 0; i < questions.length; i += batchSize) {
      const batch = questions.slice(i, i + batchSize);
      await Promise.all(
        batch.map((q) =>
          prisma.mCQQuestion.create({
            data: {
              courseId: course.id,
              question: q.question,
              options: q.options,
              answer: q.answer,
              hint: q.hint || "",
            },
          })
        )
      );
    }

    console.log(`  ✓ Done: "${course.name}" (${questions.length} questions)`);
    totalSeeded += questions.length;
  }

  console.log(
    `✅ MCQ seeding complete! (${totalSeeded} questions seeded across ${courses.length} courses)`
  );
}

main()
  .catch((err) => {
    console.error("❌ MCQ seeding failed:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
