export const siteConfig = {
  name: "Flarelap Global Foundation",
  description: "Empower people and change lives",
  url: "https://flarelap.org",
  ogImage: "/samples/community.svg",
  email: "contact@flarelap.org",
  phone: "+919729817600",
  location: "India",
  address: "Flarelap Global Foundation\nSirsal (38) Kaithal, Haryana, India. PIN- 136026.",
  navItems: [
    { label: "Home", href: "/" },
    { label: "About", href: "/about" },
    { label: "Programs", href: "/programs" },
    { label: "Education", href: "/education" },
    { label: "Impact", href: "/impact" },
    { label: "Blog", href: "/blogs" },
    { label: "Donate", href: "/donate" },
    { label: "Contact", href: "/contact" },
  ],
  links: {
  email: "mailto:contact@flarelap.org",
    x: "https://x.com/Flarelap_Org",
    facebook: "https://www.facebook.com/flarelap.org",
    youtube: "https://www.youtube.com/@flarelap_org",
    github: "https://github.com/flarelap",
  },
};
